[opener]
app_image = [
{ run = "%s", orphan = true, desc = "Run AppImage", for = "unix" }
]
pdf = [
{ run = "xreader %s", orphan = true, desc = "Open PDF", for = "unix" }
]
vlc = [
{ run = "vlc %s", orphan = true, desc = "Open MP4", for = "unix" }
]
libre = [
{ run = "org.libreoffice.LibreOffice %s", orphan = true, desc = "Open Sheets", for = "unix" }
]
eagle = [
{ run = "eagle %s", orphan = true, desc = "Open Eagle CAD", for = "unix" }
]
kicad = [
{ run = "org.kicad.KiCad %s", orphan = true, desc = "Open KiCad Prjoect", for = "unix" }
]
arduino = [
{ run = "nvim %s", orphan = true, desc = "Open .ino files", for = "unix" }
]

[open]
prepend_rules = [
{url = "*.AppImage", use = "app_image"},
{url = "*.pdf", use = "pdf"},
{url = "*.mp4", use = "vlc"},
{url = "*.csv", use = "libre"},
{url = "*.brd", use = "eagle"},
{url = "*.sch", use = "eagle"},
{url = "*.kicad_pro", use = "kicad"},
{url = "*.ino", use = "arduino"},
]

[mgr]
ratio = [2,3,3]
